import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers/AuthProvider";

const deafultFont = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Com Amor, IF",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en" className="scroll-smooth">
        <body className={deafultFont.className}>{children}</body>
      </html>
    </AuthProvider>
  );
}
